# Generated by Django 5.2.3 on 2025-06-24 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parroquia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('ubicacion', models.CharField(choices=[('norte', 'norte'), ('sur', 'sur'), ('este', 'este'), ('oeste', 'oeste')], max_length=30)),
                ('tipo', models.CharField(choices=[('urbana', 'urbana'), ('rural', 'rural')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('numero_viviendas', models.IntegerField()),
                ('numero_parques', models.IntegerField()),
                ('numero_edfre', models.IntegerField()),
                ('parroquia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenamiento.parroquia')),
            ],
        ),
    ]
