"""
Django settings for prroyectociudad project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-3)_!8!2+%w%(5fgp_l()e-qgv!k0tg31d&paj3u988^h@p!^1!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ordenamiento',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'prroyectociudad.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'prroyectociudad.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [ BASE_DIR / "static"]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Probanding Jazzmin

JAZZMIN_SETTINGS = {
    "site_title": "Taller 10 Admin",
    "site_brand": "Nahomi UwU",
    "site_logo": "img/user_avatar.jpg", 
    "login_logo": "img/login_logo.jpeg",

    "welcome_sign": "Bienvenida, guapísima 🎀",
    "copyright": "Nahomi ❤️",
    
    "topmenu_links": [
        {"name": "Inicio", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "GitHub", "url": "https://github.com/nahomi2004/Jazzmin-Django", "new_window": True},
    ],

    "usermenu_links": [
        {"name": "Mi Perfil", "url": "/admin/auth/user/", "icon": "fas fa-user-circle"},
    ],

    "icons": {
        "ordenamiento.parroquia": "fas fa-city",
        "ordenamiento.barrio": "fas fa-building",
    },

    "show_sidebar": True,
    "navigation_expanded": True,
    "order_with_respect_to": ["ordenamiento", "ordenamiento.parroquia", "ordenamiento.barrio"],

    "related_modal_active": True,
    "changeform_format": "horizontal_tabs",
}

# Personalización visual avanzada:
JAZZMIN_UI_TWEAKS = {
    "theme": "flaty", # tema claro y fresh
    "accent": "accent-pink",

    "compact_sidebar": True,
    "navigation_fixed": True,

    "sidebar_light": True,

    "navbar_small_text": False,
    "footer_small_text": True,
    "body_small_text": False,
    "brand_small_text": False,

    "navbar": "navbar-dark navbar-pink",
    "sidebar_nav_flat_style": True,

    "brand_colour": "navbar-pink",

    "no_navbar_border": True,
    "sidebar_nav_flat_style": True,
    "sidebar_nav_legacy_style": False,
}